// August 2026 — FINAL / MONTH-END CLOSE (frozen from lib/data.ts) — INLINED (do not re-import from data.ts)
// Generated by scripts/freeze-month.mjs on close. periodInfo.daysRemaining forced to 0.
import type { MonthSnapshot } from '../types'

const aug2026: MonthSnapshot = {
    key: "2026-08",
    periodInfo: {
      label: "August 2026",
      dataAsOf: "Aug 31",
      totalBizDays: 21,
      daysComplete: 21,
      daysRemaining: 0
    },
    data: {
      period: "August 2026",
      org: {
        production: 2581715,
        productionGoal: 2910000,
        collections: 1450143,
        collectionsGoal: 1455000,
        newPatients: 708,
        activePatients: 2531,
        phoneAnswerRate: 68.4,
        hygieneRecare: 95.3,
        suppliesPct: 5.7
      },
      locations: [
        { code:"LKW", production:759309, collections:374322, collectionRate:49.3, newPatients:131, recareRate:0, phoneAnswerRate: 80, activePatients:534, activeHygienePatients:6098, suppliesPct:5.52, status:"on_pace" },
        { code:"LT", production:327820, collections:141278, collectionRate:43.1, newPatients:57, recareRate:0, phoneAnswerRate: 72, activePatients:421, activeHygienePatients:3202, suppliesPct:4.39, status:"on_pace" },
        { code:"HNR", production:187508, collections:126057, collectionRate:67.2, newPatients:64, recareRate:0, phoneAnswerRate: 71, activePatients:298, activeHygienePatients:1589, suppliesPct:7.37, status:"watch" },
        { code:"HNS", production:209588, collections:108339, collectionRate:51.7, newPatients:89, recareRate:0, phoneAnswerRate: 75, activePatients:276, activeHygienePatients:541, suppliesPct:6.9, status:"on_pace" },
        { code:"HNK", production:39146, collections:53978, collectionRate:137.9, newPatients:29, recareRate:0, phoneAnswerRate: 49, activePatients:0, activeHygienePatients:427, suppliesPct:7.46, status:"watch" },
        { code:"PB", production:600253, collections:275206, collectionRate:45.8, newPatients:112, recareRate:0, phoneAnswerRate: 66, activePatients:389, activeHygienePatients:942, suppliesPct:4.08, status:"on_pace" },
        { code:"PR", production:328967, collections:154474, collectionRate:47, newPatients:145, recareRate:0, phoneAnswerRate: 61, activePatients:321, activeHygienePatients:495, suppliesPct:8.84, status:"on_pace" },
        { code:"OSB", production:129124, collections:216488, collectionRate:167.7, newPatients:81, recareRate:0, phoneAnswerRate: 69, activePatients:292, activeHygienePatients:1744, suppliesPct:6.11, status:"watch", isOSB:true }
      ],
      doctors: [
        { name:"Nichols, Christopher", locationCode:"LKW", grossProd:429248, collections:168907, collRate:39.3, prodPerDay:20440, daysWorked:21, ytdProd:2666248, patientCount:371, prodPerPatient:1157 },
        { name:"Proctor, Sarah", locationCode:"PB", grossProd:292884, collections:137817, collRate:47.1, prodPerDay:13947, daysWorked:21, ytdProd:2064884, patientCount:383, prodPerPatient:765 },
        { name:"Weathers, L'Cris", locationCode:"PR", grossProd:281596, collections:104647, collRate:37.2, prodPerDay:13409, daysWorked:21, ytdProd:1800596, patientCount:429, prodPerPatient:656 },
        { name:"Connolly, Noah", locationCode:"HNS", grossProd:224106, collections:107745, collRate:48.1, prodPerDay:10672, daysWorked:21, ytdProd:1332106, patientCount:349, prodPerPatient:642 },
        { name:"Ballard, Erin", locationCode:"PB", grossProd:218766, collections:78606, collRate:35.9, prodPerDay:10417, daysWorked:21, ytdProd:1294766, patientCount:338, prodPerPatient:647 },
        { name:"Nichols, Patrick", locationCode:"LT", grossProd:174346, collections:85697, collRate:49.2, prodPerDay:8302, daysWorked:21, ytdProd:1238346, patientCount:649, prodPerPatient:269 },
        { name:"Chadwick, Evan", locationCode:"LKW", grossProd:127980, collections:60212, collRate:47, prodPerDay:6094, daysWorked:21, ytdProd:716980, patientCount:775, prodPerPatient:165 },
        { name:"Skaggs, Ernest", locationCode:"HNR", grossProd:78617, collections:55624, collRate:70.8, prodPerDay:3744, daysWorked:21, ytdProd:594617, patientCount:295, prodPerPatient:266 },
        { name:"Decker Haycraft, Kara", locationCode:"LT", grossProd:74004, collections:38615, collRate:52.2, prodPerDay:3524, daysWorked:21, ytdProd:541004, patientCount:380, prodPerPatient:195 },
        { name:"Gleason, Robert", locationCode:"HNR", grossProd:57883, collections:33484, collRate:57.8, prodPerDay:2756, daysWorked:21, ytdProd:508883, patientCount:311, prodPerPatient:186 },
        { name:"Werner, Andrew", locationCode:"OSB", grossProd:49706, collections:9235, collRate:18.6, prodPerDay:2367, daysWorked:21, ytdProd:49706, patientCount:355, prodPerPatient:140, isOSB:true },
        { name:"Walters, Carrie", locationCode:"LKW", grossProd:47439, collections:36432, collRate:76.8, prodPerDay:2259, daysWorked:21, ytdProd:777439, patientCount:478, prodPerPatient:99 },
        { name:"Osbourne, Brian", locationCode:"OSB", grossProd:35629, collections:67950, collRate:190.7, prodPerDay:1697, daysWorked:21, ytdProd:843629, patientCount:1070, prodPerPatient:33, isOSB:true },
        { name:"King, Susan", locationCode:"HNK", grossProd:12396, collections:19880, collRate:160.4, prodPerDay:590, daysWorked:21, ytdProd:157396, patientCount:211, prodPerPatient:59, isOSB:true },
        { name:"Harvey, Mark", locationCode:"LKW", grossProd:10568, collections:6843, collRate:64.8, prodPerDay:503, daysWorked:21, ytdProd:34568, patientCount:270, prodPerPatient:39 }
      ],
      hygienists: [
        { name:"Woosley, Emily", locationCode:"LKW", grossProd:24591, collections:13221, collRate:53.8, hoursWorked:154.03, prodPerHr:160, recareRate:0, patientCount:190, prodPerPatient:129 },
        { name:"Smith, Berlyn", locationCode:"LKW", grossProd:22718, collections:14022, collRate:61.7, hoursWorked:138.51, prodPerHr:164, recareRate:0, patientCount:174, prodPerPatient:131 },
        { name:"Miller, Jenna", locationCode:"LKW", grossProd:21249, collections:10561, collRate:49.7, hoursWorked:135.25, prodPerHr:157, recareRate:0, patientCount:165, prodPerPatient:129 },
        { name:"Berry, Tasha", locationCode:"LKW", grossProd:17750, collections:11625, collRate:65.5, hoursWorked:112.79, prodPerHr:157, recareRate:0, patientCount:176, prodPerPatient:101 },
        { name:"Kimble, Cheryl", locationCode:"LKW", grossProd:16088, collections:11534, collRate:71.7, hoursWorked:106.93, prodPerHr:150, recareRate:0, patientCount:162, prodPerPatient:99 },
        { name:"Payne, McKay", locationCode:"LKW", grossProd:15502, collections:11378, collRate:73.4, hoursWorked:118.38, prodPerHr:131, recareRate:0, patientCount:171, prodPerPatient:91 },
        { name:"Vowels, Susan", locationCode:"LKW", grossProd:9174, collections:5522, collRate:60.2, hoursWorked:70.3, prodPerHr:130, recareRate:0, patientCount:86, prodPerPatient:107 },
        { name:"Murphy, Sherry", locationCode:"LKW", grossProd:4018, collections:3587, collRate:89.3, hoursWorked:31.6, prodPerHr:127, recareRate:0, patientCount:57, prodPerPatient:70 },
        { name:"Wright, Chelsea", locationCode:"LKW", grossProd:1536, collections:1144, collRate:74.5, hoursWorked:161.02, prodPerHr:10, recareRate:0, patientCount:25, prodPerPatient:61 },
        { name:"Bewley, Emma", locationCode:"LKW", grossProd:410, collections:3017, collRate:735.9, hoursWorked:0, prodPerHr:0, recareRate:0, patientCount:41, prodPerPatient:10 },
        { name:"Howell, Dana", locationCode:"LT", grossProd:20530, collections:8373, collRate:40.8, hoursWorked:146.18, prodPerHr:140, recareRate:0, patientCount:166, prodPerPatient:124 },
        { name:"Blandford, Cassi", locationCode:"LT", grossProd:18211, collections:7216, collRate:39.6, hoursWorked:143.39, prodPerHr:127, recareRate:0, patientCount:162, prodPerPatient:112 },
        { name:"Harned, Stacy", locationCode:"LT", grossProd:15217, collections:5265, collRate:34.6, hoursWorked:104.37, prodPerHr:146, recareRate:0, patientCount:116, prodPerPatient:131 },
        { name:"Youart, Britney", locationCode:"LT", grossProd:8777, collections:2698, collRate:30.7, hoursWorked:65.06, prodPerHr:135, recareRate:0, patientCount:69, prodPerPatient:127 },
        { name:"Kittle, Jolena", locationCode:"LT", grossProd:8339, collections:4787, collRate:57.4, hoursWorked:65.63, prodPerHr:127, recareRate:0, patientCount:85, prodPerPatient:98 },
        { name:"Buzick, Rebecca", locationCode:"LT", grossProd:6414, collections:2977, collRate:46.4, hoursWorked:43.34, prodPerHr:148, recareRate:0, patientCount:54, prodPerPatient:119 },
        { name:"Morris, Amber", locationCode:"HNR", grossProd:24088, collections:8184, collRate:34, hoursWorked:151.23, prodPerHr:159, recareRate:0, patientCount:179, prodPerPatient:135 },
        { name:"Lynch, Cassie", locationCode:"HNR", grossProd:20408, collections:12235, collRate:60, hoursWorked:120.68, prodPerHr:169, recareRate:0, patientCount:174, prodPerPatient:117 },
        { name:"Logsdon, Megan", locationCode:"HNS", grossProd:24116, collections:11111, collRate:46.1, hoursWorked:155.54, prodPerHr:155, recareRate:0, patientCount:143, prodPerPatient:169 },
        { name:"Miller, Taylor", locationCode:"HNK", grossProd:8756, collections:5198, collRate:59.4, hoursWorked:131.67, prodPerHr:66, recareRate:0, patientCount:157, prodPerPatient:56, isOSB:true },
        { name:"Decker, Heather", locationCode:"HNK", grossProd:0, collections:1344, collRate:0, hoursWorked:13.98, prodPerHr:0, recareRate:0, patientCount:37, prodPerPatient:0, isOSB:true },
        { name:"Keehan, Joshua", locationCode:"PB", grossProd:59594, collections:36542, collRate:61.3, hoursWorked:136.3, prodPerHr:437, recareRate:0, patientCount:268, prodPerPatient:222 },
        { name:"Jones, Chad", locationCode:"PR", grossProd:44370, collections:18476, collRate:41.6, hoursWorked:136.69, prodPerHr:325, recareRate:0, patientCount:222, prodPerPatient:200 },
        { name:"Ulrich, Leigh", locationCode:"OSB", grossProd:8316, collections:3805, collRate:45.8, hoursWorked:137.18, prodPerHr:61, recareRate:0, patientCount:178, prodPerPatient:47, isOSB:true },
        { name:"Culver, Angela", locationCode:"OSB", grossProd:7841, collections:4251, collRate:54.2, hoursWorked:140.71, prodPerHr:56, recareRate:0, patientCount:189, prodPerPatient:41, isOSB:true },
        { name:"Haydon, Kelsey", locationCode:"OSB", grossProd:6796, collections:5005, collRate:73.7, hoursWorked:143.05, prodPerHr:48, recareRate:0, patientCount:204, prodPerPatient:33, isOSB:true },
        { name:"Yates, Jaclyn", locationCode:"OSB", grossProd:6571, collections:3187, collRate:48.5, hoursWorked:110.06, prodPerHr:60, recareRate:0, patientCount:168, prodPerPatient:39, isOSB:true },
        { name:"Smith, Jessica", locationCode:"OSB", grossProd:4866, collections:2454, collRate:50.4, hoursWorked:89.44, prodPerHr:54, recareRate:0, patientCount:114, prodPerPatient:43, isOSB:true },
        { name:"Greenwell, Denise", locationCode:"OSB", grossProd:1158, collections:2950, collRate:254.7, hoursWorked:43.28, prodPerHr:27, recareRate:0, patientCount:88, prodPerPatient:13, isOSB:true }
      ],
      phones: [
        { code:"LKW", totalCalls:1882, answered:1501, missed:381, answerRate:80, estMissedRevenue:0 },
        { code:"LT", totalCalls:1043, answered:755, missed:288, answerRate:72, estMissedRevenue:0 },
        { code:"HNR", totalCalls:1009, answered:714, missed:295, answerRate:71, estMissedRevenue:0 },
        { code:"HNS", totalCalls:702, answered:525, missed:177, answerRate:75, estMissedRevenue:0 },
        { code:"HNK", totalCalls:961, answered:470, missed:491, answerRate:49, estMissedRevenue:0 },
        { code:"PB", totalCalls:1566, answered:1040, missed:526, answerRate:66, estMissedRevenue:0 },
        { code:"PR", totalCalls:1516, answered:920, missed:596, answerRate:61, estMissedRevenue:0 },
        { code:"OSB", totalCalls:1354, answered:937, missed:417, answerRate:69, estMissedRevenue:0 }
      ],
      ar: {
        asOf: "08/31/2026",
        healthScore: 70,
        total: 1848487,
        buckets: {
          d0_30: 1296433,
          d31_60: 300990,
          d61_90: 233098,
          d90plus: 355839
        },
        pcts: {
          d0_30: 59.29,
          d31_60: 13.77,
          d61_90: 10.66,
          d90plus: 16.28
        },
        arToProdRatio: 0.71,
        locations: [
          { code:"LKW", total:586860, d0_30:367195, d31_60:101495, d61_90:96625, d90plus:180878, pct0_30:49.21, pct31_60:13.6, pct61_90:12.95, pct90plus:24.24, insuranceAR:167772, patientAR:404746, patientPct:71, arToProd:0.91, status:"needs_work" },
          { code:"HNK", total:85778, d0_30:65380, d31_60:11873, d61_90:7617, d90plus:6016, pct0_30:71.94, pct31_60:13.06, pct61_90:8.38, pct90plus:6.62, insuranceAR:33059, patientAR:33252, patientPct:50, arToProd:1.18, status:"good" },
          { code:"LT", total:226181, d0_30:163192, d31_60:30527, d61_90:19934, d90plus:40898, pct0_30:64.11, pct31_60:11.99, pct61_90:7.83, pct90plus:16.07, insuranceAR:93638, patientAR:43372, patientPct:32, arToProd:0.8, status:"watch" },
          { code:"HNR", total:219892, d0_30:143829, d31_60:50308, d61_90:30650, d90plus:44344, pct0_30:53.44, pct31_60:18.69, pct61_90:11.39, pct90plus:16.48, insuranceAR:99419, patientAR:91903, patientPct:48, arToProd:1.24, status:"watch" },
          { code:"HNS", total:45023, d0_30:39501, d31_60:12079, d61_90:1550, d90plus:8792, pct0_30:63.79, pct31_60:19.51, pct61_90:2.5, pct90plus:14.2, insuranceAR:21342, patientAR:24969, patientPct:54, arToProd:0.28, status:"good" },
          { code:"OSB", total:227605, d0_30:141128, d31_60:50723, d61_90:41982, d90plus:9447, pct0_30:58.01, pct31_60:20.85, pct61_90:17.26, pct90plus:3.88, insuranceAR:91886, patientAR:82865, patientPct:47, arToProd:1.03, status:"watch", isOSB:true },
          { code:"PB", total:280732, d0_30:240129, d31_60:36546, d61_90:29059, d90plus:37073, pct0_30:70.05, pct31_60:10.66, pct61_90:8.48, pct90plus:10.81, insuranceAR:127130, patientAR:84695, patientPct:40, arToProd:0.39, status:"good" },
          { code:"PR", total:176414, d0_30:136078, d31_60:7439, d61_90:5683, d90plus:28391, pct0_30:76.62, pct31_60:4.19, pct61_90:3.2, pct90plus:15.99, insuranceAR:64930, patientAR:100030, patientPct:61, arToProd:0.54, status:"watch" }
        ]
      }
    },
    partial: true
  }

export default aug2026
