// July 2026 — FINAL / MONTH-END CLOSE (frozen from lib/data.ts) — INLINED (do not re-import from data.ts)
// Generated by scripts/freeze-month.mjs on close. periodInfo.daysRemaining forced to 0.
import type { MonthSnapshot } from '../types'

const jul2026: MonthSnapshot = {
    key: "2026-07",
    periodInfo: {
      label: "July 2026",
      dataAsOf: "Jul 31",
      totalBizDays: 22,
      daysComplete: 22,
      daysRemaining: 0
    },
    data: {
      period: "July 2026",
      org: {
        production: 2597555,
        productionGoal: 2400000,
        collections: 1362082,
        collectionsGoal: 1455000,
        newPatients: 701,
        activePatients: 2531,
        phoneAnswerRate: 63.1,
        hygieneRecare: 95.3,
        suppliesPct: 6.3
      },
      locations: [
        { code:"LKW", production:646662, collections:327895, collectionRate:50.7, newPatients:128, recareRate:0, phoneAnswerRate:76, activePatients:534, suppliesPct:6.28, status:"on_pace" },
        { code:"LT", production:282271, collections:187847, collectionRate:66.5, newPatients:56, recareRate:0, phoneAnswerRate:67, activePatients:421, suppliesPct:5, status:"on_pace" },
        { code:"HNR", production:176829, collections:119861, collectionRate:67.8, newPatients:72, recareRate:0, phoneAnswerRate:51, activePatients:298, suppliesPct:3.29, status:"on_pace" },
        { code:"HNS", production:159602, collections:87610, collectionRate:54.9, newPatients:59, recareRate:0, phoneAnswerRate:60, activePatients:276, suppliesPct:6.83, status:"watch" },
        { code:"HNK", production:72668, collections:59506, collectionRate:81.9, newPatients:45, recareRate:0, phoneAnswerRate:45, activePatients:0, suppliesPct:4.87, status:"watch" },
        { code:"PB", production:713827, collections:253174, collectionRate:35.5, newPatients:136, recareRate:0, phoneAnswerRate:71, activePatients:389, suppliesPct:9.34, status:"on_pace" },
        { code:"PR", production:323924, collections:125445, collectionRate:38.7, newPatients:132, recareRate:0, phoneAnswerRate:55, activePatients:321, suppliesPct:5.5, status:"on_pace" },
        { code:"OSB", production:221771, collections:200744, collectionRate:90.5, newPatients:73, recareRate:0, phoneAnswerRate:67, activePatients:292, suppliesPct:0.56, status:"watch", isOSB:true }
      ],
      doctors: [
        { name:"Nichols, Christopher", locationCode:"LKW", grossProd:301302, collections:152213, collRate:50.5, prodPerDay:13696, daysWorked:22, ytdProd:2237000, patientCount:349, prodPerPatient:863 },
        { name:"Proctor, Sarah", locationCode:"PB", grossProd:261543, collections:97674, collRate:37.3, prodPerDay:11888, daysWorked:22, ytdProd:1772000, patientCount:401, prodPerPatient:652 },
        { name:"Weathers, L'Cris", locationCode:"PR", grossProd:248864, collections:90338, collRate:36.3, prodPerDay:11312, daysWorked:22, ytdProd:1519000, patientCount:358, prodPerPatient:695 },
        { name:"Ballard, Erin", locationCode:"PB", grossProd:240340, collections:98971, collRate:41.2, prodPerDay:10925, daysWorked:22, ytdProd:1076000, patientCount:424, prodPerPatient:567 },
        { name:"Connolly, Noah", locationCode:"HNS", grossProd:195284, collections:104939, collRate:53.7, prodPerDay:8877, daysWorked:22, ytdProd:1108000, patientCount:352, prodPerPatient:555 },
        { name:"Nichols, Patrick", locationCode:"LT", grossProd:175667, collections:115425, collRate:65.7, prodPerDay:7985, daysWorked:22, ytdProd:1064000, patientCount:781, prodPerPatient:225 },
        { name:"Osbourne, Brian", locationCode:"OSB", grossProd:163515, collections:126711, collRate:77.5, prodPerDay:7433, daysWorked:22, ytdProd:808000, patientCount:1178, prodPerPatient:139, isOSB:true },
        { name:"Walters, Carrie", locationCode:"LKW", grossProd:126113, collections:69193, collRate:54.9, prodPerDay:5732, daysWorked:22, ytdProd:730000, patientCount:675, prodPerPatient:187 },
        { name:"Chadwick, Evan", locationCode:"LKW", grossProd:116511, collections:48724, collRate:41.8, prodPerDay:5296, daysWorked:22, ytdProd:589000, patientCount:606, prodPerPatient:192 },
        { name:"Gleason, Robert", locationCode:"HNR", grossProd:84132, collections:53242, collRate:63.3, prodPerDay:3824, daysWorked:22, ytdProd:451000, patientCount:305, prodPerPatient:276 },
        { name:"Decker Haycraft, Kara", locationCode:"LT", grossProd:76424, collections:38434, collRate:50.3, prodPerDay:3474, daysWorked:22, ytdProd:467000, patientCount:363, prodPerPatient:211 },
        { name:"Skaggs, Ernest", locationCode:"HNR", grossProd:72285, collections:49094, collRate:67.9, prodPerDay:3286, daysWorked:22, ytdProd:516000, patientCount:299, prodPerPatient:242 },
        { name:"King, Susan", locationCode:"HNK", grossProd:28559, collections:31041, collRate:108.7, prodPerDay:1298, daysWorked:22, ytdProd:145000, patientCount:203, prodPerPatient:141 },
        { name:"Harvey, Mark", locationCode:"LKW", grossProd:3976, collections:3111, collRate:78.2, prodPerDay:181, daysWorked:22, ytdProd:24000, patientCount:175, prodPerPatient:23 }
      ],
      hygienists: [
        { name:"Kimble, Cheryl", locationCode:"LKW", grossProd:25902, collections:11697, collRate:45.2, hoursWorked:151.08, prodPerHr:171, recareRate:0, patientCount:177, prodPerPatient:146 },
        { name:"Berry, Tasha", locationCode:"LKW", grossProd:20789, collections:9625, collRate:46.3, hoursWorked:125.89, prodPerHr:165, recareRate:0, patientCount:170, prodPerPatient:122 },
        { name:"Smith, Berlyn", locationCode:"LKW", grossProd:27287, collections:10693, collRate:39.2, hoursWorked:155.96, prodPerHr:175, recareRate:0, patientCount:187, prodPerPatient:146 },
        { name:"Woosley, Emily", locationCode:"LKW", grossProd:21618, collections:11339, collRate:52.5, hoursWorked:136.25, prodPerHr:159, recareRate:0, patientCount:191, prodPerPatient:113 },
        { name:"Payne, McKay", locationCode:"LKW", grossProd:20034, collections:9242, collRate:46.1, hoursWorked:137.52, prodPerHr:146, recareRate:0, patientCount:168, prodPerPatient:119 },
        { name:"Vowels, Susan", locationCode:"LKW", grossProd:6544, collections:4950, collRate:75.6, hoursWorked:44.67, prodPerHr:146, recareRate:0, patientCount:83, prodPerPatient:79 },
        { name:"Bewley, Emma", locationCode:"LKW", grossProd:9120, collections:6147, collRate:67.4, hoursWorked:67.16, prodPerHr:136, recareRate:0, patientCount:94, prodPerPatient:97 },
        { name:"Wright, Chelsea", locationCode:"LKW", grossProd:4568, collections:2976, collRate:65.2, hoursWorked:113.06, prodPerHr:40, recareRate:0, patientCount:47, prodPerPatient:97 },
        { name:"Murphy, Sherry", locationCode:"LKW", grossProd:3720, collections:1925, collRate:51.7, hoursWorked:22.41, prodPerHr:166, recareRate:0, patientCount:49, prodPerPatient:76 },
        { name:"Blandford, Cassi", locationCode:"LT", grossProd:17371, collections:9730, collRate:56, hoursWorked:123.22, prodPerHr:141, recareRate:0, patientCount:160, prodPerPatient:109 },
        { name:"Harned, Stacy", locationCode:"LT", grossProd:15853, collections:9519, collRate:60, hoursWorked:108.08, prodPerHr:147, recareRate:0, patientCount:143, prodPerPatient:111 },
        { name:"Howell, Dana", locationCode:"LT", grossProd:13539, collections:10188, collRate:75.2, hoursWorked:112.59, prodPerHr:120, recareRate:0, patientCount:189, prodPerPatient:72 },
        { name:"Kittle, Jolena", locationCode:"LT", grossProd:15529, collections:8080, collRate:52, hoursWorked:99.63, prodPerHr:156, recareRate:0, patientCount:113, prodPerPatient:137 },
        { name:"Youart, Britney", locationCode:"LT", grossProd:7615, collections:4758, collRate:62.5, hoursWorked:56.01, prodPerHr:136, recareRate:0, patientCount:65, prodPerPatient:117 },
        { name:"Buzick, Rebecca", locationCode:"LT", grossProd:9650, collections:3774, collRate:39.1, hoursWorked:64.84, prodPerHr:149, recareRate:0, patientCount:68, prodPerPatient:142 },
        { name:"Morris, Amber", locationCode:"HNR", grossProd:12821, collections:12908, collRate:100.7, hoursWorked:90.9, prodPerHr:141, recareRate:0, patientCount:173, prodPerPatient:74 },
        { name:"Lynch, Cassie", locationCode:"HNR", grossProd:22163, collections:11303, collRate:51, hoursWorked:133.74, prodPerHr:166, recareRate:0, patientCount:177, prodPerPatient:125 },
        { name:"Logsdon, Megan", locationCode:"HNS", grossProd:17647, collections:9953, collRate:56.4, hoursWorked:113.89, prodPerHr:155, recareRate:0, patientCount:123, prodPerPatient:143 },
        { name:"Miller, Taylor", locationCode:"HNK", grossProd:13026, collections:11675, collRate:89.6, hoursWorked:125.92, prodPerHr:103, recareRate:0, patientCount:143, prodPerPatient:91 },
        { name:"Decker, Heather", locationCode:"HNK", grossProd:3827, collections:2335, collRate:61, hoursWorked:25.66, prodPerHr:149, recareRate:0, patientCount:41, prodPerPatient:93 },
        { name:"Keehan, Joshua", locationCode:"PB", grossProd:72218, collections:22776, collRate:31.5, hoursWorked:155.64, prodPerHr:464, recareRate:0, patientCount:289, prodPerPatient:250 },
        { name:"Wires, Tanya", locationCode:"PB", grossProd:0, collections:388, collRate:0, hoursWorked:0, prodPerHr:0, recareRate:0, patientCount:0, prodPerPatient:0 },
        { name:"Jones, Chad", locationCode:"PR", grossProd:35089, collections:13567, collRate:38.7, hoursWorked:81.01, prodPerHr:433, recareRate:0, patientCount:177, prodPerPatient:198 },
        { name:"Haydon, Kelsey", locationCode:"OSB", grossProd:11457, collections:10176, collRate:88.8, hoursWorked:145.39, prodPerHr:79, recareRate:0, patientCount:190, prodPerPatient:60, isOSB:true },
        { name:"Culver, Angela", locationCode:"OSB", grossProd:6439, collections:11739, collRate:182.3, hoursWorked:131.06, prodPerHr:49, recareRate:0, patientCount:204, prodPerPatient:32, isOSB:true },
        { name:"Yates, Jaclyn", locationCode:"OSB", grossProd:7708, collections:8858, collRate:114.9, hoursWorked:124.93, prodPerHr:62, recareRate:0, patientCount:175, prodPerPatient:44, isOSB:true },
        { name:"Ulrich, Leigh", locationCode:"OSB", grossProd:8538, collections:7035, collRate:82.4, hoursWorked:102.75, prodPerHr:83, recareRate:0, patientCount:130, prodPerPatient:66, isOSB:true },
        { name:"Greenwell, Denise", locationCode:"OSB", grossProd:7862, collections:5635, collRate:71.7, hoursWorked:77.07, prodPerHr:102, recareRate:0, patientCount:89, prodPerPatient:88, isOSB:true },
        { name:"Smith, Jessica", locationCode:"OSB", grossProd:5221, collections:4802, collRate:92, hoursWorked:77.11, prodPerHr:68, recareRate:0, patientCount:115, prodPerPatient:45, isOSB:true }
      ],
      phones: [
        { code:"LKW", totalCalls:1668, answered:1262, missed:406, answerRate:76, estMissedRevenue:0 },
        { code:"LT", totalCalls:901, answered:607, missed:294, answerRate:67, estMissedRevenue:0 },
        { code:"HNR", totalCalls:1063, answered:544, missed:519, answerRate:51, estMissedRevenue:0 },
        { code:"HNS", totalCalls:505, answered:305, missed:200, answerRate:60, estMissedRevenue:0 },
        { code:"HNK", totalCalls:894, answered:400, missed:494, answerRate:45, estMissedRevenue:0 },
        { code:"PB", totalCalls:1317, answered:933, missed:384, answerRate:71, estMissedRevenue:0 },
        { code:"PR", totalCalls:1161, answered:639, missed:522, answerRate:55, estMissedRevenue:0 },
        { code:"OSB", totalCalls:1178, answered:794, missed:384, answerRate:67, estMissedRevenue:0 }
      ],
      ar: {
        asOf: "07/31/2026",
        healthScore: 69,
        total: 1958622,
        buckets: {
          d0_30: 1348181,
          d31_60: 399863,
          d61_90: 159529,
          d90plus: 365136
        },
        pcts: {
          d0_30: 59.32,
          d31_60: 17.59,
          d61_90: 7.02,
          d90plus: 16.07
        },
        arToProdRatio: 0.7,
        locations: [
          { code:"LKW", total:552015, d0_30:306208, d31_60:139946, d61_90:67909, d90plus:176061, pct0_30:44.37, pct31_60:20.28, pct61_90:9.84, pct90plus:25.51, insuranceAR:185798, patientAR:350314, patientPct:65, arToProd:0.8, status:"needs_work" },
          { code:"HNK", total:72577, d0_30:52010, d31_60:15388, d61_90:11007, d90plus:384, pct0_30:66.01, pct31_60:19.53, pct61_90:13.97, pct90plus:0.49, insuranceAR:31809, patientAR:21302, patientPct:40, arToProd:1.1, status:"good" },
          { code:"LT", total:173940, d0_30:127580, d31_60:26167, d61_90:9131, d90plus:41070, pct0_30:62.55, pct31_60:12.83, pct61_90:4.48, pct90plus:20.14, insuranceAR:69514, patientAR:40727, patientPct:37, arToProd:0.6, status:"watch" },
          { code:"HNR", total:229375, d0_30:133838, d31_60:66312, d61_90:20389, d90plus:44766, pct0_30:50.45, pct31_60:24.99, pct61_90:7.69, pct90plus:16.87, insuranceAR:100636, patientAR:87509, patientPct:47, arToProd:1.1, status:"watch" },
          { code:"HNS", total:62743, d0_30:58415, d31_60:2493, d61_90:4489, d90plus:6182, pct0_30:81.61, pct31_60:3.48, pct61_90:6.27, pct90plus:8.64, insuranceAR:29000, patientAR:16321, patientPct:36, arToProd:0.7, status:"good" },
          { code:"OSB", total:395035, d0_30:271158, d31_60:90994, d61_90:27031, d90plus:29736, pct0_30:64.73, pct31_60:21.72, pct61_90:6.45, pct90plus:7.1, insuranceAR:144307, patientAR:86369, patientPct:37, arToProd:1.4, status:"watch", isOSB:true },
          { code:"PB", total:266733, d0_30:245580, d31_60:45665, d61_90:13952, d90plus:29230, pct0_30:73.43, pct31_60:13.65, pct61_90:4.17, pct90plus:8.74, insuranceAR:120425, patientAR:97580, patientPct:45, arToProd:0.4, status:"watch" },
          { code:"PR", total:206204, d0_30:153393, d31_60:12898, d61_90:5621, d90plus:37707, pct0_30:73.18, pct31_60:6.15, pct61_90:2.68, pct90plus:17.99, insuranceAR:67143, patientAR:120678, patientPct:64, arToProd:0.7, status:"watch" }
        ]
      }
    },
    partial: true
  }

export default jul2026
