// September 2026 — FINAL / MONTH-END CLOSE (frozen from lib/data.ts) — INLINED (do not re-import from data.ts)
// Generated by scripts/freeze-month.mjs on close. periodInfo.daysRemaining forced to 0.
import type { MonthSnapshot } from '../types'

const sep2026: MonthSnapshot = {
    key: "2026-09",
    periodInfo: {
      label: "September 2026",
      dataAsOf: "Sep 30 (FINAL)",
      totalBizDays: 21,
      daysComplete: 21,
      daysRemaining: 0
    },
    data: {
      period: "September 2026",
      org: {
        production: 3088151,
        productionGoal: 3217500,
        collections: 1469936,
        collectionsGoal: 1495000,
        newPatients: 660,
        activePatients: 2531,
        phoneAnswerRate: 67.6,
        hygieneRecare: 95.3,
        suppliesPct: 5.7
      },
      asOf: {
        phones: "Sep 30",
        supplies: "Aug 14",
        activeHygiene: "Sep 30"
      },
      locations: [
        { code:"LKW", production:775503, collections:393910, collectionRate:50.8, newPatients:149, newPatientsGoal:120, recareRate:0, phoneAnswerRate:75, activePatients:534, activeHygienePatients:5040, suppliesPct:5.52, status:"on_pace" },
        { code:"LT", production:281706, collections:194004, collectionRate:68.9, newPatients:64, newPatientsGoal:80, recareRate:0, phoneAnswerRate:73, activePatients:421, activeHygienePatients:2916, suppliesPct:4.39, status:"on_pace" },
        { code:"HNR", production:200923, collections:94036, collectionRate:46.8, newPatients:70, newPatientsGoal:80, recareRate:0, phoneAnswerRate:76, activePatients:298, activeHygienePatients:1476, suppliesPct:7.37, status:"on_pace" },
        { code:"HNS", production:266959, collections:105798, collectionRate:39.6, newPatients:65, newPatientsGoal:40, recareRate:0, phoneAnswerRate:75, activePatients:276, activeHygienePatients:568, suppliesPct:6.9, status:"watch" },
        { code:"HNK", production:147540, collections:40301, collectionRate:27.3, newPatients:45, newPatientsGoal:40, recareRate:0, phoneAnswerRate:64, activePatients:0, activeHygienePatients:513, suppliesPct:7.46, status:"watch" },
        { code:"PB", production:603560, collections:256491, collectionRate:42.5, newPatients:89, newPatientsGoal:120, recareRate:0, phoneAnswerRate:63, activePatients:389, activeHygienePatients:921, suppliesPct:4.08, status:"on_pace" },
        { code:"PR", production:516416, collections:220662, collectionRate:42.7, newPatients:121, newPatientsGoal:80, recareRate:0, phoneAnswerRate:49, activePatients:321, activeHygienePatients:566, suppliesPct:8.84, status:"on_pace" },
        { code:"OSB", production:295544, collections:164734, collectionRate:55.7, newPatients:57, newPatientsGoal:80, recareRate:0, phoneAnswerRate:74, activePatients:292, activeHygienePatients:2197, suppliesPct:6.11, status:"on_pace", isOSB:true }
      ],
      doctors: [
        { name:"Nichols, Christopher", locationCode:"LKW", grossProd:375552, collections:188472, collRate:50.2, prodPerDay:17883, daysWorked:21, ytdProd:3041800, patientCount:364, prodPerPatient:1032 },
        { name:"Proctor, Sarah", locationCode:"PB", grossProd:285472, collections:142066, collRate:49.8, prodPerDay:13594, daysWorked:21, ytdProd:2350356, patientCount:377, prodPerPatient:757 },
        { name:"Weathers, L'Cris", locationCode:"PR", grossProd:260958, collections:121573, collRate:46.6, prodPerDay:12427, daysWorked:21, ytdProd:2061554, patientCount:321, prodPerPatient:813 },
        { name:"Connolly, Noah", locationCode:"HNS", grossProd:238325, collections:104791, collRate:44, prodPerDay:11349, daysWorked:21, ytdProd:1570431, patientCount:301, prodPerPatient:792 },
        { name:"Ballard, Erin", locationCode:"PB", grossProd:217021, collections:88928, collRate:41, prodPerDay:10334, daysWorked:21, ytdProd:1511787, patientCount:302, prodPerPatient:719 },
        { name:"Nichols, Patrick", locationCode:"LT", grossProd:197691, collections:121374, collRate:61.4, prodPerDay:9414, daysWorked:21, ytdProd:1436037, patientCount:831, prodPerPatient:238 },
        { name:"Walters, Carrie", locationCode:"LKW", grossProd:138501, collections:61462, collRate:44.4, prodPerDay:6595, daysWorked:21, ytdProd:915940, patientCount:600, prodPerPatient:231 },
        { name:"Bone, Victoria", locationCode:"PR", grossProd:135948, collections:39898, collRate:29.3, prodPerDay:6474, daysWorked:21, ytdProd:135948, patientCount:162, prodPerPatient:839 },
        { name:"Chadwick, Evan", locationCode:"LKW", grossProd:108993, collections:61706, collRate:56.6, prodPerDay:5190, daysWorked:21, ytdProd:825973, patientCount:685, prodPerPatient:159 },
        { name:"Osbourne, Brian", locationCode:"OSB", grossProd:107136, collections:77677, collRate:72.5, prodPerDay:5102, daysWorked:21, ytdProd:950765, patientCount:754, prodPerPatient:142, isOSB:true },
        { name:"Werner, Andrew", locationCode:"OSB", grossProd:88081, collections:39260, collRate:44.6, prodPerDay:4194, daysWorked:21, ytdProd:137787, patientCount:460, prodPerPatient:191, isOSB:true },
        { name:"Skaggs, Ernest", locationCode:"HNR", grossProd:80455, collections:32902, collRate:40.9, prodPerDay:3831, daysWorked:21, ytdProd:675072, patientCount:259, prodPerPatient:311 },
        { name:"Decker Haycraft, Kara", locationCode:"LT", grossProd:76808, collections:35178, collRate:45.8, prodPerDay:3658, daysWorked:21, ytdProd:617812, patientCount:385, prodPerPatient:200 },
        { name:"Gleason, Robert", locationCode:"HNR", grossProd:73802, collections:43407, collRate:58.8, prodPerDay:3514, daysWorked:21, ytdProd:582685, patientCount:329, prodPerPatient:224 },
        { name:"Morgan, Kennedy", locationCode:"PB", grossProd:73757, collections:26983, collRate:36.6, prodPerDay:3512, daysWorked:21, ytdProd:187178, patientCount:186, prodPerPatient:397 },
        { name:"King, Susan", locationCode:"HNK", grossProd:59792, collections:20757, collRate:34.7, prodPerDay:2847, daysWorked:21, ytdProd:228904, patientCount:171, prodPerPatient:350 },
        { name:"Harvey, Mark", locationCode:"LKW", grossProd:4675, collections:2978, collRate:63.7, prodPerDay:223, daysWorked:21, ytdProd:39243, patientCount:134, prodPerPatient:35 }
      ],
      hygienists: [
        { name:"Keehan, Joshua", locationCode:"PB", grossProd:68120, collections:32463, collRate:47.7, hoursWorked:142.62, prodPerHr:478, recareRate:0, patientCount:250, prodPerPatient:272 },
        { name:"Jones, Chad", locationCode:"PR", grossProd:46014, collections:21267, collRate:46.2, hoursWorked:138.71, prodPerHr:332, recareRate:0, patientCount:214, prodPerPatient:215 },
        { name:"Lynch, Cassie", locationCode:"HNR", grossProd:24635, collections:7608, collRate:30.9, hoursWorked:149.6, prodPerHr:165, recareRate:0, patientCount:193, prodPerPatient:128 },
        { name:"Woosley, Emily", locationCode:"LKW", grossProd:23691, collections:11531, collRate:48.7, hoursWorked:154.42, prodPerHr:153, recareRate:0, patientCount:198, prodPerPatient:120 },
        { name:"Berry, Tasha", locationCode:"LKW", grossProd:22113, collections:9446, collRate:42.7, hoursWorked:141.51, prodPerHr:156, recareRate:0, patientCount:168, prodPerPatient:132 },
        { name:"Ferguson, Amie", locationCode:"LKW", grossProd:22085, collections:7237, collRate:32.8, hoursWorked:138.09, prodPerHr:160, recareRate:0, patientCount:125, prodPerPatient:177 },
        { name:"Logsdon, Megan", locationCode:"HNS", grossProd:21550, collections:9652, collRate:44.8, hoursWorked:143, prodPerHr:151, recareRate:0, patientCount:123, prodPerPatient:175 },
        { name:"Ulrich, Leigh", locationCode:"OSB", grossProd:21097, collections:9040, collRate:42.8, hoursWorked:130.87, prodPerHr:161, recareRate:0, patientCount:159, prodPerPatient:133, isOSB:true },
        { name:"Miller, Jenna", locationCode:"LKW", grossProd:20893, collections:8533, collRate:40.8, hoursWorked:87.27, prodPerHr:239, recareRate:0, patientCount:165, prodPerPatient:127 },
        { name:"Howell, Dana", locationCode:"LT", grossProd:20358, collections:11885, collRate:58.4, hoursWorked:135.21, prodPerHr:151, recareRate:0, patientCount:197, prodPerPatient:103 },
        { name:"Smith, Berlyn", locationCode:"LKW", grossProd:19642, collections:7787, collRate:39.6, hoursWorked:138.88, prodPerHr:141, recareRate:0, patientCount:158, prodPerPatient:124 },
        { name:"Miller, Taylor", locationCode:"HNK", grossProd:19357, collections:4519, collRate:23.3, hoursWorked:127.81, prodPerHr:151, recareRate:0, patientCount:122, prodPerPatient:159 },
        { name:"Haydon, Kelsey", locationCode:"OSB", grossProd:17935, collections:9311, collRate:51.9, hoursWorked:106.14, prodPerHr:169, recareRate:0, patientCount:156, prodPerPatient:115, isOSB:true },
        { name:"Blandford, Cassi", locationCode:"LT", grossProd:17933, collections:9588, collRate:53.5, hoursWorked:138.66, prodPerHr:129, recareRate:0, patientCount:179, prodPerPatient:100 },
        { name:"Yates, Jaclyn", locationCode:"OSB", grossProd:17866, collections:7080, collRate:39.6, hoursWorked:112.61, prodPerHr:159, recareRate:0, patientCount:149, prodPerPatient:120, isOSB:true },
        { name:"Payne, McKay", locationCode:"LKW", grossProd:17602, collections:8469, collRate:48.1, hoursWorked:124.27, prodPerHr:142, recareRate:0, patientCount:140, prodPerPatient:126 },
        { name:"Morris, Amber", locationCode:"HNR", grossProd:17317, collections:8440, collRate:48.7, hoursWorked:137.52, prodPerHr:126, recareRate:0, patientCount:201, prodPerPatient:86 },
        { name:"Culver, Angela", locationCode:"OSB", grossProd:14948, collections:8313, collRate:55.6, hoursWorked:90.89, prodPerHr:164, recareRate:0, patientCount:141, prodPerPatient:106, isOSB:true },
        { name:"Harned, Stacy", locationCode:"LT", grossProd:12628, collections:8918, collRate:70.6, hoursWorked:94.15, prodPerHr:134, recareRate:0, patientCount:132, prodPerPatient:96 },
        { name:"Smith, Jessica", locationCode:"OSB", grossProd:12465, collections:5464, collRate:43.8, hoursWorked:83.31, prodPerHr:150, recareRate:0, patientCount:106, prodPerPatient:118, isOSB:true },
        { name:"Kittle, Jolena", locationCode:"LT", grossProd:11538, collections:6745, collRate:58.5, hoursWorked:71.98, prodPerHr:160, recareRate:0, patientCount:103, prodPerPatient:112 },
        { name:"Youart, Britney", locationCode:"LT", grossProd:9891, collections:6179, collRate:62.5, hoursWorked:71.43, prodPerHr:138, recareRate:0, patientCount:99, prodPerPatient:100 },
        { name:"Buzick, Rebecca", locationCode:"LT", grossProd:9514, collections:5152, collRate:54.2, hoursWorked:55.83, prodPerHr:170, recareRate:0, patientCount:67, prodPerPatient:142 },
        { name:"Vowels, Susan", locationCode:"LKW", grossProd:9429, collections:4295, collRate:45.6, hoursWorked:59.03, prodPerHr:160, recareRate:0, patientCount:86, prodPerPatient:110 },
        { name:"Kimble, Cheryl", locationCode:"LKW", grossProd:8693, collections:6210, collRate:71.4, hoursWorked:59.63, prodPerHr:146, recareRate:0, patientCount:89, prodPerPatient:98 },
        { name:"Greenwell, Denise", locationCode:"OSB", grossProd:7761, collections:2894, collRate:37.3, hoursWorked:42.04, prodPerHr:185, recareRate:0, patientCount:67, prodPerPatient:116, isOSB:true },
        { name:"Murphy, Sherry", locationCode:"LKW", grossProd:5670, collections:2446, collRate:43.1, hoursWorked:45.84, prodPerHr:124, recareRate:0, patientCount:50, prodPerPatient:113 },
        { name:"Spencer, Rachel", locationCode:"HNR", grossProd:5300, collections:2332, collRate:44, hoursWorked:31.33, prodPerHr:169, recareRate:0, patientCount:37, prodPerPatient:143 },
        { name:"Decker, Heather", locationCode:"HNK", grossProd:3076, collections:864, collRate:28.1, hoursWorked:14.03, prodPerHr:219, recareRate:0, patientCount:24, prodPerPatient:128 },
        { name:"Wright, Chelsea", locationCode:"LKW", grossProd:1414, collections:526, collRate:37.2, hoursWorked:155.19, prodPerHr:9, recareRate:0, patientCount:14, prodPerPatient:101 },
        { name:"Bewley, Emma", locationCode:"LKW", grossProd:0, collections:914, collRate:0, hoursWorked:0, prodPerHr:0, recareRate:0, patientCount:13, prodPerPatient:0 }
      ],
      phones: [
        { code:"LKW", totalCalls:1875, answered:1409, missed:466, answerRate:75, estMissedRevenue:0 },
        { code:"LT", totalCalls:979, answered:712, missed:267, answerRate:73, estMissedRevenue:0 },
        { code:"HNR", totalCalls:965, answered:737, missed:228, answerRate:76, estMissedRevenue:0 },
        { code:"HNS", totalCalls:645, answered:484, missed:161, answerRate:75, estMissedRevenue:0 },
        { code:"HNK", totalCalls:699, answered:446, missed:253, answerRate:64, estMissedRevenue:0 },
        { code:"PB", totalCalls:1452, answered:921, missed:531, answerRate:63, estMissedRevenue:0 },
        { code:"PR", totalCalls:1628, answered:794, missed:834, answerRate:49, estMissedRevenue:0 },
        { code:"OSB", totalCalls:1129, answered:830, missed:299, answerRate:74, estMissedRevenue:0 }
      ],
      ar: {
        asOf: "09/30/2026",
        healthScore: 66,
        total: 1930731,
        buckets: {
          d0_30: 1277698,
          d31_60: 360734,
          d61_90: 163006,
          d90plus: 440254
        },
        pcts: {
          d0_30: 57,
          d31_60: 16.09,
          d61_90: 7.27,
          d90plus: 19.64
        },
        arToProdRatio: 0.73,
        locations: [
          { code:"LKW", total:562188, d0_30:330452, d31_60:124690, d61_90:62274, d90plus:218696, pct0_30:44.89, pct31_60:16.94, pct61_90:8.46, pct90plus:29.71, insuranceAR:192445, patientAR:543667, patientPct:74, arToProd:0.74, status:"needs_work" },
          { code:"LT", total:169536, d0_30:129026, d31_60:21061, d61_90:6221, d90plus:34811, pct0_30:67.51, pct31_60:11.02, pct61_90:3.25, pct90plus:18.21, insuranceAR:72985, patientAR:118133, patientPct:62, arToProd:0.52, status:"good" },
          { code:"HNR", total:272026, d0_30:156206, d31_60:68282, d61_90:36011, d90plus:58499, pct0_30:48.97, pct31_60:21.41, pct61_90:11.29, pct90plus:18.34, insuranceAR:135129, patientAR:183869, patientPct:58, arToProd:1.45, status:"needs_work" },
          { code:"HNS", total:79299, d0_30:65514, d31_60:7976, d61_90:9341, d90plus:8037, pct0_30:72.1, pct31_60:8.78, pct61_90:10.28, pct90plus:8.84, insuranceAR:35567, patientAR:55302, patientPct:61, arToProd:0.38, status:"good" },
          { code:"HNK", total:150611, d0_30:94935, d31_60:47810, d61_90:7041, d90plus:8735, pct0_30:59.89, pct31_60:30.16, pct61_90:4.44, pct90plus:5.51, insuranceAR:70604, patientAR:87917, patientPct:55, arToProd:2.24, status:"watch" },
          { code:"PB", total:311022, d0_30:238781, d31_60:45126, d61_90:11614, d90plus:51340, pct0_30:68.84, pct31_60:13.01, pct61_90:3.35, pct90plus:14.8, insuranceAR:138865, patientAR:207996, patientPct:60, arToProd:0.52, status:"good" },
          { code:"PR", total:171577, d0_30:130184, d31_60:7453, d61_90:4598, d90plus:31971, pct0_30:74.73, pct31_60:4.28, pct61_90:2.64, pct90plus:18.35, insuranceAR:57456, patientAR:116749, patientPct:67, arToProd:0.52, status:"good" },
          { code:"OSB", total:214473, d0_30:132599, d31_60:38338, d61_90:25907, d90plus:28165, pct0_30:58.93, pct31_60:17.04, pct61_90:11.51, pct90plus:12.52, insuranceAR:86519, patientAR:138489, patientPct:62, arToProd:1.35, status:"watch", isOSB:true }
        ]
      }
    }
  }

export default sep2026
