#!/usr/bin/env node
// Freeze the current live month (lib/data.ts) into lib/months/<key>.ts as a MonthSnapshot,
// and register it in lib/history.ts. Run at month-end close AFTER the final daily update.
//
// Usage:
//   node scripts/freeze-month.mjs --key 2026-07 --var jul2026 --label "July 2026" [--partial] [--register]
//
// Without --register it only writes the month file (so you can eyeball it first).
// Idempotent-ish: refuses to overwrite an existing month file unless --force.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import Module from 'node:module'
import ts from 'typescript'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const args = Object.fromEntries(process.argv.slice(2).flatMap((a, i, arr) =>
  a.startsWith('--') ? [[a.slice(2), arr[i + 1] && !arr[i + 1].startsWith('--') ? arr[i + 1] : true]] : []))

const key   = args.key   || required('--key (e.g. 2026-07)')
const varNm = args.var   || required('--var (e.g. jul2026)')
const label = args.label || required('--label (e.g. "July 2026")')
function required(n){ console.error('Missing '+n); process.exit(1) }

// 1. Transpile lib/data.ts (types are `import type`, erased) and load its exports.
const src = fs.readFileSync(path.join(root, 'lib/data.ts'), 'utf8')
const js  = ts.transpileModule(src, { compilerOptions: { module: 'CommonJS', target: 'ES2020' } }).outputText
const m   = new Module('data-snapshot'); m._compile(js, 'data.ts')
const { PERIOD_INFO, DEMO_DATA } = m.exports
if (!PERIOD_INFO || !DEMO_DATA) { console.error('Could not read PERIOD_INFO / DEMO_DATA from data.ts'); process.exit(1) }

// 2. Build the snapshot object (data = DEMO_DATA, periodInfo = PERIOD_INFO with period label locked).
const snapshot = {
  key,
  periodInfo: { ...PERIOD_INFO, label, daysRemaining: 0 },
  data: DEMO_DATA,
  ...(args.partial ? { partial: true } : {}),
}

// 3. Serialize with the project's compact one-object-per-line style for arrays of records.
const body = serialize(snapshot, 1)
const header =
`// ${label} — FINAL / MONTH-END CLOSE (frozen from lib/data.ts) — INLINED (do not re-import from data.ts)
// Generated by scripts/freeze-month.mjs on close. periodInfo.daysRemaining forced to 0.
import type { MonthSnapshot } from '../types'

const ${varNm}: MonthSnapshot = ${body}

export default ${varNm}
`
const outPath = path.join(root, 'lib/months', `${key}.ts`)
if (fs.existsSync(outPath) && !args.force) { console.error(`${outPath} exists — pass --force to overwrite`); process.exit(1) }
fs.writeFileSync(outPath, header)
console.log('wrote', path.relative(root, outPath), `(prod $${DEMO_DATA.org.production.toLocaleString()}, coll $${DEMO_DATA.org.collections.toLocaleString()}, NP ${DEMO_DATA.org.newPatients})`)

// 4. Optionally register in history.ts.
if (args.register) {
  const hp = path.join(root, 'lib/history.ts')
  let h = fs.readFileSync(hp, 'utf8')
  if (h.includes(`months/${key}`)) { console.log('history.ts already imports', key); }
  else {
    // add import after the last existing months import
    h = h.replace(/(import [a-z0-9]+ from '\.\/months\/[0-9-]+'\n)(?![\s\S]*import [a-z0-9]+ from '\.\/months)/,
      `$1import ${varNm} from './months/${key}'\n`)
    // append to HISTORICAL_MONTHS array: insert a clean line right before the closing ']'
    // (existing last entry already carries a trailing comma; TS allows the new trailing comma too)
    h = h.replace(/(\n)(\]\n\nexport const LATEST_MONTH)/, `$1  ${varNm},$1$2`)
    fs.writeFileSync(hp, h)
    console.log('registered', varNm, 'in history.ts (verify the array + import)')
  }
}

// ---- helpers ----
function serialize(v, indent) {
  const pad = '  '.repeat(indent)
  if (Array.isArray(v)) {
    if (v.length && v.every(x => x && typeof x === 'object' && !Array.isArray(x))) {
      // array of records → one per line, inline
      return '[\n' + v.map(x => pad + '  ' + inlineObj(x)).join(',\n') + '\n' + pad + ']'
    }
    return '[' + v.map(x => serialize(x, indent)).join(', ') + ']'
  }
  if (v && typeof v === 'object') {
    const keys = Object.keys(v)
    return '{\n' + keys.map(k => `${pad}  ${k}: ${serialize(v[k], indent + 1)}`).join(',\n') + '\n' + pad + '}'
  }
  return JSON.stringify(v)
}
function inlineObj(o) {
  return '{ ' + Object.entries(o).map(([k, val]) => `${k}:${typeof val === 'string' ? JSON.stringify(val) : val}`).join(', ') + ' }'
}
